import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import TVShimmerBackground from "@/components/TVShimmerBackground";
import Navbar from "@/components/Navbar";

// Replace Geist with Montserrat
const montserrat = Montserrat({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-sans antialiased`}>
        <TVShimmerBackground />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
